### ISSUE TITLE
Empty report

### ISSUE THREAD

**Issue by yuke1922** [AsBuiltReport/AsBuiltReport.Aruba.ClearPass#10]
Running against a 6.12.0 cluster

No errors in this log but report shows up empty.
`Enter a name for the As Built Report configuration file [AsBuiltReport]:
Enter the path to save the As Built Report configuration file [C:\Users\Luke.McCormick\AsBuiltReport]:
VERBOSE: Saving As Built Report configuration file 'AsBuiltReport.json' to path
'C:\Users\Luke.McCormick\AsBuiltReport'.
VERBOSE: Config.Report.Author = Luke.McCormick
VERBOSE: Config.UserFolder.Path = C:\Users\Luke.McCormick\AsBuiltReport
VERBOSE: Config.Company.FullName =
VERBOSE: Config.Company.Contact =
VERBOSE: Config.Company.Phone =
VERBOSE: Config.Company.Email =
VERBOSE: Config.Company.ShortName =
VERBOSE: Config.Company.Address =
VERBOSE: Config.Email.Port =
VERBOSE: Config.Email.Credentials =
VERBOSE: Config.Email.Server =
VERBOSE: Config.Email.To =
VERBOSE: Config.Email.From =
VERBOSE: Config.Email.UseSSL =
VERBOSE: Config.Email.Body =
VERBOSE: Populating RepositorySourceLocation property for module AsBuiltReport.Aruba.ClearPass.
VERBOSE: Loading module from path 'C:\Program
Files\WindowsPowerShell\Modules\AsBuiltReport.Aruba.ClearPass\0.1.1\AsBuiltReport.Aruba.ClearPass.psm1'.
VERBOSE: Loading report configuration file from path 'C:\Program
Files\WindowsPowerShell\Modules\AsBuiltReport.Aruba.ClearPass\0.1.1\AsBuiltReport.Aruba.ClearPass.json'.
VERBOSE: Setting report filename to 'Aruba ClearPass As Built Report - 2024-02-01_13.20.04'.
VERBOSE: [ 13:20:04:770 ] [ Document ] - Document 'Aruba ClearPass As Built Report - 2024-02-01_13.20.04' processing
started.
VERBOSE: [ 13:20:04:937 ] [ Document ] - Executing report style script from path 'C:\Program
Files\WindowsPowerShell\Modules\AsBuiltReport.Aruba.ClearPass\0.1.1\AsBuiltReport.Aruba.ClearPass.Style.ps1'.
VERBOSE: [ 13:20:04:952 ] [ Document ] - Setting global document options.
VERBOSE: [ 13:20:04:968 ] [ Document ] - Enabling section/heading numbering.
VERBOSE: [ 13:20:04:968 ] [ Document ] - Setting default font(s) to 'Arial'.
VERBOSE: [ 13:20:04:968 ] [ Document ] - Setting page top margin to '25.05'mm.
VERBOSE: [ 13:20:04:968 ] [ Document ] - Setting page right margin to '25.05'mm.
VERBOSE: [ 13:20:04:968 ] [ Document ] - Setting page bottom margin to '25.05'mm.
VERBOSE: [ 13:20:04:968 ] [ Document ] - Setting page left margin to '25.05'mm.
VERBOSE: [ 13:20:04:968 ] [ Document ] - Setting page size to 'A4'.
VERBOSE: [ 13:20:04:984 ] [ Document ] - Setting page orientation to 'Portrait'.
VERBOSE: [ 13:20:04:984 ] [ Document ] - Setting page height to '297'mm.
VERBOSE: [ 13:20:04:984 ] [ Document ] - Setting page width to '210'mm.
VERBOSE: [ 13:20:04:984 ] [ Document ] - Setting document style 'Title'.
VERBOSE: [ 13:20:04:984 ] [ Document ] - Setting document style 'Title2'.
VERBOSE: [ 13:20:04:984 ] [ Document ] - Setting document style 'Title3'.
VERBOSE: [ 13:20:04:999 ] [ Document ] - Setting document style 'Heading1'.
VERBOSE: [ 13:20:04:999 ] [ Document ] - Setting document style 'Heading2'.
VERBOSE: [ 13:20:04:999 ] [ Document ] - Setting document style 'Heading3'.
VERBOSE: [ 13:20:04:999 ] [ Document ] - Setting document style 'Heading4'.
VERBOSE: [ 13:20:05:015 ] [ Document ] - Setting document style 'Heading5'.
VERBOSE: [ 13:20:05:015 ] [ Document ] - Setting document style 'Normal'.
VERBOSE: [ 13:20:05:015 ] [ Document ] - Setting document style 'Caption'.
VERBOSE: [ 13:20:05:031 ] [ Document ] - Setting document style 'Header'.
VERBOSE: [ 13:20:05:031 ] [ Document ] - Setting document style 'Footer'.
VERBOSE: [ 13:20:05:037 ] [ Document ] - Setting document style 'TOC'.
VERBOSE: [ 13:20:05:037 ] [ Document ] - Setting document style 'TableDefaultHeading'.
VERBOSE: [ 13:20:05:037 ] [ Document ] - Setting document style 'TableDefaultRow'.
VERBOSE: [ 13:20:05:037 ] [ Document ] - Setting document style 'Critical'.
VERBOSE: [ 13:20:05:037 ] [ Document ] - Setting document style 'Warning'.
VERBOSE: [ 13:20:05:053 ] [ Document ] - Setting document style 'Info'.
VERBOSE: [ 13:20:05:053 ] [ Document ] - Setting document style 'OK'.
VERBOSE: [ 13:20:05:053 ] [ Document ] - Setting table style 'TableDefault'.
VERBOSE: [ 13:20:05:053 ] [ Document ] - Setting table style 'Borderless'.
VERBOSE: [ 13:20:05:084 ] [ Document ] - Processing document header started.
VERBOSE: [ 13:20:05:131 ] [ Document ] - Processing paragraph 'Aruba ClearPass As Built Report - v1.0'.
VERBOSE: [ 13:20:05:177 ] [ Document ] - Processing document header completed.
VERBOSE: [ 13:20:05:193 ] [ Document ] - Processing document footer started.
VERBOSE: [ 13:20:05:193 ] [ Document ] - Processing paragraph 'Page <!# PageNumber #!>'.
VERBOSE: [ 13:20:05:209 ] [ Document ] - Processing document footer completed.
VERBOSE: [ 13:20:05:224 ] [ Document ] - Processing blank line.
VERBOSE: [ 13:20:05:253 ] [ Document ] - Processing image 'AsBuiltReport Logo'.
VERBOSE: [ 13:20:05:316 ] [ Document ] - Processing blank line.
VERBOSE: [ 13:20:05:316 ] [ Document ] - Processing paragraph 'Aruba ClearPass As Built Report'.
VERBOSE: [ 13:20:05:331 ] [ Document ] - Processing blank line.
VERBOSE: [ 13:20:05:353 ] [ Document ] - Processing table 'Cover Page'.
VERBOSE: [ 13:20:05:369 ] [ Document ] - Processing page break.
VERBOSE: [ 13:20:05:384 ] [ Document ] - Processing table of contents 'Table of Contents'.
VERBOSE: [ 13:20:05:384 ] [ Document ] - Processing page break.
VERBOSE: [ 13:20:05:384 ] [  Module  ] - Please refer to the AsBuiltReport.Aruba.ClearPass GitHub website for more
detailed information about this project.
VERBOSE: [ 13:20:05:400 ] [  Module  ] - Do not forget to update your report configuration file after each new version
release: https://www.asbuiltreport.com/user-guide/new-asbuiltreportconfig/
VERBOSE: [ 13:20:05:400 ] [  Module  ] - Documentation: https://github.com/AsBuiltReport/AsBuiltReport.Aruba.ClearPass
VERBOSE: [ 13:20:05:400 ] [  Module  ] - Issues or bug reporting:
https://github.com/AsBuiltReport/AsBuiltReport.Aruba.ClearPass/issues
VERBOSE: [ 13:20:05:427 ] [  Module  ] - AsBuiltReport.Aruba.ClearPass 0.1.1 is currently installed.
VERBOSE: [ 13:20:11:459 ] [ Document ] - Connect to tips.lmccormick.com : LMCPPM01.lmccormick.com
VERBOSE: [ 13:20:11:474 ] [ Document ] - Processing section 'Implementation Report LMCPPM01.lmccormick.com' started.
VERBOSE: [ 13:20:11:490 ] [ Document ] - Processing paragraph 'The following section provides a sum[..]'.
VERBOSE: [ 13:20:11:506 ] [ Document ] - Processing blank line.
VERBOSE: [ 13:20:11:506 ] [ Document ] - Discovering System settings information from tips.lmccormick.com.
VERBOSE: [ 13:20:12:306 ] [ Document ] - Processing section 'Version' started.
VERBOSE: [ 13:20:12:315 ] [ Document ] - Processing paragraph 'The following section details Versio[..]'.
VERBOSE: [ 13:20:12:323 ] [ Document ] - Processing blank line.
VERBOSE: [ 13:20:12:331 ] [ Document ] - Processing table 'Version'.
VERBOSE: [ 13:20:12:377 ] [ Document ] - Processing paragraph 'The following section details Patche[..]'.
VERBOSE: [ 13:20:12:393 ] [ Document ] - Processing blank line.
VERBOSE: [ 13:20:12:393 ] [ Document ] - Processing table 'Patches'.
WARNING: [ 13:20:12:409 ] [ Document ] - Cannot bind argument to parameter 'Rows' because it is an empty collection.
VERBOSE: [ 13:20:12:424 ] [ Document ] - Document 'Aruba ClearPass As Built Report - 2024-02-01_13.20.04' processing
completed.
VERBOSE: [ 13:20:12:440 ] [ Document ] - Total processing time '7.73' seconds.`

**Comment by alagoutte** [comment]
Thanks @yuke1922, there is an issue with 6.x.0 (when there is no patches), it will be fixed soon
